"""initial schema

Revision ID: e468c490bbaf
Revises: 
Create Date: 2026-03-10 20:14:43.536005

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e468c490bbaf'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('industries',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('registration_no', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('region_office_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('active', 'suspended', name='industrystatus'), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_industries_id'), 'industries', ['id'], unique=False)
    op.create_index(op.f('ix_industries_name'), 'industries', ['name'], unique=False)
    op.create_index(op.f('ix_industries_registration_no'), 'industries', ['registration_no'], unique=True)
    op.create_table('monitoring_units',
    sa.Column('parameter', sa.String(), nullable=False),
    sa.Column('unit', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_monitoring_units_id'), 'monitoring_units', ['id'], unique=False)
    op.create_index(op.f('ix_monitoring_units_parameter'), 'monitoring_units', ['parameter'], unique=False)
    op.create_table('regional_offices',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('district', sa.String(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('coordinates', sa.String(), nullable=True),
    sa.Column('officer_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_regional_offices_id'), 'regional_offices', ['id'], unique=False)
    op.create_table('users',
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('super_admin', 'regional_officer', 'monitoring_team', 'industry_user', 'citizen', name='userrole'), nullable=False),
    sa.Column('region_office_id', sa.UUID(), nullable=True),
    sa.Column('industry_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['industry_id'], ['industries.id'], ),
    sa.ForeignKeyConstraint(['region_office_id'], ['regional_offices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_foreign_key('fk_industries_region_office_id', 'industries', 'regional_offices', ['region_office_id'], ['id'])
    op.create_foreign_key('fk_regional_offices_officer_id', 'regional_offices', 'users', ['officer_id'], ['id'])
    op.create_table('compliance_records',
    sa.Column('industry_id', sa.UUID(), nullable=False),
    sa.Column('parameter_id', sa.UUID(), nullable=False),
    sa.Column('period', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('compliant', 'non_compliant', 'pending', name='compliancestatus'), nullable=False),
    sa.Column('violations_count', sa.Integer(), nullable=True),
    sa.Column('last_checked', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['industry_id'], ['industries.id'], ),
    sa.ForeignKeyConstraint(['parameter_id'], ['monitoring_units.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_compliance_records_id'), 'compliance_records', ['id'], unique=False)
    op.create_table('industrial_monitoring_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('industry_id', sa.UUID(), nullable=False),
    sa.Column('parameter_id', sa.UUID(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('unit_id', sa.UUID(), nullable=False),
    sa.Column('reported_by', sa.UUID(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('report_type', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['industry_id'], ['industries.id'], ),
    sa.ForeignKeyConstraint(['parameter_id'], ['monitoring_units.id'], ),
    sa.ForeignKeyConstraint(['reported_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['unit_id'], ['monitoring_units.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('missing_report_reminders',
    sa.Column('industry_id', sa.UUID(), nullable=False),
    sa.Column('report_type', sa.String(), nullable=False),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['industry_id'], ['industries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_missing_report_reminders_id'), 'missing_report_reminders', ['id'], unique=False)
    op.create_table('monitoring_campaigns',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('region_id', sa.UUID(), nullable=False),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('frequency', sa.String(), nullable=True),
    sa.Column('team_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['region_id'], ['regional_offices.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('monitoring_locations',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('type', sa.Enum('air', 'water', 'noise', name='locationtype'), nullable=False),
    sa.Column('industry_id', sa.UUID(), nullable=True),
    sa.Column('region_id', sa.UUID(), nullable=True),
    sa.Column('iot_device_id', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['industry_id'], ['industries.id'], ),
    sa.ForeignKeyConstraint(['region_id'], ['regional_offices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_monitoring_locations_id'), 'monitoring_locations', ['id'], unique=False)
    op.create_index(op.f('ix_monitoring_locations_iot_device_id'), 'monitoring_locations', ['iot_device_id'], unique=True)
    op.create_table('periodic_reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('report_type', sa.String(), nullable=False),
    sa.Column('region_id', sa.UUID(), nullable=False),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('pdf_url', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['region_id'], ['regional_offices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prescribed_limits',
    sa.Column('parameter_id', sa.UUID(), nullable=False),
    sa.Column('industry_type', sa.String(), nullable=False),
    sa.Column('limit_value', sa.Float(), nullable=False),
    sa.Column('limit_type', sa.Enum('max', 'min', name='limittype'), nullable=False),
    sa.Column('effective_from', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['parameter_id'], ['monitoring_units.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prescribed_limits_id'), 'prescribed_limits', ['id'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_tokens_id'), 'refresh_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_token_hash'), 'refresh_tokens', ['token_hash'], unique=False)
    op.create_table('water_sources',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('region_office_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['region_office_id'], ['regional_offices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_water_sources_id'), 'water_sources', ['id'], unique=False)
    op.create_table('alerts',
    sa.Column('type', sa.Enum('limit_breach', 'missing_report', 'anomaly', 'rapid_rise', 'sensor_offline', name='alerttype'), nullable=False),
    sa.Column('location_id', sa.UUID(), nullable=True),
    sa.Column('industry_id', sa.UUID(), nullable=True),
    sa.Column('parameter_id', sa.UUID(), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('threshold', sa.Float(), nullable=True),
    sa.Column('severity', sa.Enum('low', 'medium', 'high', 'critical', name='alertseverity'), nullable=False),
    sa.Column('status', sa.Enum('open', 'escalated', 'resolved', name='alertstatus'), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['industry_id'], ['industries.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['monitoring_locations.id'], ),
    sa.ForeignKeyConstraint(['parameter_id'], ['monitoring_units.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_id'), 'alerts', ['id'], unique=False)
    op.create_index(op.f('ix_alerts_industry_id'), 'alerts', ['industry_id'], unique=False)
    op.create_index(op.f('ix_alerts_severity'), 'alerts', ['severity'], unique=False)
    op.create_index(op.f('ix_alerts_status'), 'alerts', ['status'], unique=False)
    op.create_table('campaign_readings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('campaign_id', sa.UUID(), nullable=False),
    sa.Column('location_id', sa.UUID(), nullable=False),
    sa.Column('parameter_id', sa.UUID(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('submitted_by', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['monitoring_campaigns.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['monitoring_locations.id'], ),
    sa.ForeignKeyConstraint(['parameter_id'], ['monitoring_units.id'], ),
    sa.ForeignKeyConstraint(['submitted_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('forecasts',
    sa.Column('location_id', sa.UUID(), nullable=False),
    sa.Column('parameter_id', sa.UUID(), nullable=False),
    sa.Column('horizon_hours', sa.Integer(), nullable=False),
    sa.Column('point_forecast', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('lower_bound', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('upper_bound', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('model_version', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['monitoring_locations.id'], ),
    sa.ForeignKeyConstraint(['parameter_id'], ['monitoring_units.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_forecasts_id'), 'forecasts', ['id'], unique=False)
    op.create_table('sensor_readings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('location_id', sa.UUID(), nullable=False),
    sa.Column('parameter_id', sa.UUID(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('unit_id', sa.UUID(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.Enum('iot', 'manual', name='sourcetype'), nullable=False),
    sa.Column('quality_flag', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['monitoring_locations.id'], ),
    sa.ForeignKeyConstraint(['parameter_id'], ['monitoring_units.id'], ),
    sa.ForeignKeyConstraint(['unit_id'], ['monitoring_units.id'], ),
    sa.PrimaryKeyConstraint('id', 'recorded_at')
    )
    op.create_index(op.f('ix_sensor_readings_location_id'), 'sensor_readings', ['location_id'], unique=False)
    op.create_index(op.f('ix_sensor_readings_parameter_id'), 'sensor_readings', ['parameter_id'], unique=False)
    op.create_table('alert_escalations',
    sa.Column('alert_id', sa.UUID(), nullable=False),
    sa.Column('escalated_to', sa.UUID(), nullable=False),
    sa.Column('escalated_by', sa.UUID(), nullable=True),
    sa.Column('escalated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], ),
    sa.ForeignKeyConstraint(['escalated_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['escalated_to'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alert_escalations_id'), 'alert_escalations', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_regional_offices_officer_id', 'regional_offices', type_='foreignkey')
    op.drop_constraint('fk_industries_region_office_id', 'industries', type_='foreignkey')
    op.drop_index(op.f('ix_alert_escalations_id'), table_name='alert_escalations')
    op.drop_table('alert_escalations')
    op.drop_index(op.f('ix_sensor_readings_parameter_id'), table_name='sensor_readings')
    op.drop_index(op.f('ix_sensor_readings_location_id'), table_name='sensor_readings')
    op.drop_table('sensor_readings')
    op.drop_index(op.f('ix_forecasts_id'), table_name='forecasts')
    op.drop_table('forecasts')
    op.drop_table('campaign_readings')
    op.drop_index(op.f('ix_alerts_status'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_severity'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_industry_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_id'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_water_sources_id'), table_name='water_sources')
    op.drop_table('water_sources')
    op.drop_index(op.f('ix_refresh_tokens_token_hash'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_id'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_prescribed_limits_id'), table_name='prescribed_limits')
    op.drop_table('prescribed_limits')
    op.drop_table('periodic_reports')
    op.drop_index(op.f('ix_monitoring_locations_iot_device_id'), table_name='monitoring_locations')
    op.drop_index(op.f('ix_monitoring_locations_id'), table_name='monitoring_locations')
    op.drop_table('monitoring_locations')
    op.drop_table('monitoring_campaigns')
    op.drop_index(op.f('ix_missing_report_reminders_id'), table_name='missing_report_reminders')
    op.drop_table('missing_report_reminders')
    op.drop_table('industrial_monitoring_logs')
    op.drop_index(op.f('ix_compliance_records_id'), table_name='compliance_records')
    op.drop_table('compliance_records')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_regional_offices_id'), table_name='regional_offices')
    op.drop_table('regional_offices')
    op.drop_index(op.f('ix_monitoring_units_parameter'), table_name='monitoring_units')
    op.drop_index(op.f('ix_monitoring_units_id'), table_name='monitoring_units')
    op.drop_table('monitoring_units')
    op.drop_index(op.f('ix_industries_registration_no'), table_name='industries')
    op.drop_index(op.f('ix_industries_name'), table_name='industries')
    op.drop_index(op.f('ix_industries_id'), table_name='industries')
    op.drop_table('industries')
    # ### end Alembic commands ###
